module.exports = {
  rules: {
    'array-bracket-newline': ['error', {multiline: true, minItems: 3}],
    'array-bracket-spacing': ['error', 'never'],
    'array-element-newline': ['error', {multiline: true, minItems: 3}],
    'block-spacing': 'error',
    'brace-style': ['error', '1tbs', {allowSingleLine: true}],
    camelcase: 'error',
    'capitalized-comments': 'off',
    'comma-spacing': 'error',
    'comma-style': ['error', 'last'],
    'computed-property-spacing': 'off',
    'consistent-this': ['error', 'self'],
    'eol-last': 'error',
    'func-call-spacing': ['error', 'never'],
    'func-name-matching': 'off',
    'func-names': 'off',
    'func-style': ['off', 'declaration'],
    'id-blacklist': ['off', 'data', 'err', 'e', 'cb', 'callback'],
    'id-length': 'off',
    'id-match': 'off',
    indent: ['error', 2, {SwitchCase: 1}],
    'jsx-quotes': ['error', 'prefer-double'],
    'key-spacing': ['error', {beforeColon: false, afterColon: true}],
    'keyword-spacing': 'error',
    'lines-around-comment': 'off',
    'line-comment-position': [
      'off',
      {
        position: 'above',
        ignorePattern: '',
        applyDefaultPatterns: true,
      },
    ],
    'linebreak-style': ['off', 'unix'],
    'max-nested-callbacks': ['off', 2],
    'multiline-ternary': 'off',
    'new-cap': ['error', {newIsCap: true, capIsNew: false}],
    'new-parens': 'error',
    'newline-per-chained-call': 'off',
    'no-array-constructor': 'error',
    'no-continue': 'off',
    'no-inline-comments': 'off',
    'no-lonely-if': 'off',
    'no-mixed-operators': 'error',
    'no-mixed-spaces-and-tabs': ['error', false],
    'no-multi-assign': 'error',
    'no-multiple-empty-lines': ['off', {max: 2}],
    'no-nested-ternary': 'off',
    'no-negated-condition': 'error',
    'no-new-object': 'error',
    'no-restricted-syntax': 'off',
    'no-tabs': 'error',
    'no-ternary': 'off',
    'no-trailing-spaces': 'error',
    'no-underscore-dangle': [
      'error',
      {
        allow: [],
        allowAfterThis: false,
        allowAfterSuper: false,
        enforceInMethodNames: true,
      },
    ],
    'no-unneeded-ternary': 'off',
    'no-whitespace-before-property': 'error',
    'nonblock-statement-body-position': 'off',
    'object-curly-newline': 'off',
    'object-curly-spacing': 'off',
    'one-var': 'off',
    'one-var-declaration-per-line': ['off', 'always'],
    'operator-assignment': ['off', 'always'],
    'operator-linebreak': 'off',
    'padded-blocks': 'off',
    'padding-line-between-statements': 'off',
    'quote-props': ['error', 'as-needed'],
    quotes: ['error', 'single', 'avoid-escape'],
    'require-jsdoc': 'off',
    semi: 'off',
    'semi-spacing': ['error', {before: false, after: true}],
    'semi-style': ['error', 'last'],
    'sort-keys': ['off', 'asc', {caseSensitive: false, natural: true}],
    'sort-vars': 'off',
    'sort-imports': 'off',
    'space-before-blocks': ['error', 'always'],
    'space-before-function-paren': ['error', 'never'],
    'space-in-parens': ['error', 'never'],
    'space-infix-ops': 'error',
    'space-unary-ops': ['error', {words: true, nonwords: false}],
    'spaced-comment': ['error', 'always'],
    'switch-colon-spacing': ['error', {after: true, before: false}],
    'template-tag-spacing': ['error', 'never'],
    'unicode-bom': ['off', 'never'],
    'wrap-regex': 'off',
  },
};
